name: whatsapp-chat-analysis
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py39h9128911_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - ca-certificates=2024.7.2=haa95532_0
  - contourpy=1.2.0=py39h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.51.0=py39h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - icu=73.1=h6c2663c_0
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.8.4=py39haa95532_0
  - matplotlib-base=3.8.4=py39h4ed8f06_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - numexpr=2.8.7=py39h2cd9be0_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.4.0=h4afccc4_2
  - openssl=3.0.14=h827c3e9_0
  - packaging=24.1=py39haa95532_0
  - pandas=2.2.2=py39h5da7b33_0
  - pillow=10.4.0=py39h827c3e9_0
  - pip=24.0=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.10=py39hd77b12b_0
  - pyqt5-sip=12.13.0=py39h2bbff1b_0
  - python=3.9.19=h1aa4202_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py39haa95532_0
  - qt-main=5.15.2=h19c9488_10
  - seaborn=0.13.2=py39haa95532_0
  - setuptools=69.5.1=py39haa95532_0
  - sip=6.7.12=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.4.1=py39h827c3e9_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h2bbff1b_0
  - vc=14.2=h2eaa2aa_4
  - vs2015_runtime=14.29.30133=h43f2093_4
  - wheel=0.43.0=py39haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zipp=3.17.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
prefix: C:\Users\pubgp\.conda\envs\whatsapp-chat-analysis
